print("Описание переменной:" "user_name")
print("Заголовок заметки:" "title")
print("Описание заметки:" "content")
print("Статус заметки:" "status")
print("Дата создания заметки:" "created_date")
print("Дата истечения заметки:" "issure_date")